all:
  children:

    servers:
      hosts:
        goku:
          ansible_host: goku.lan
          description: "Main server"
          ansible_user: robyn
          machine_type: server
          ansible_become_exe: sudo.ws # Ubuntu 26.04 uses sudo-rs instead of sudo... this makes it so it goes back to old sudo which is now called sudo.ws

        zoro:
          ansible_host: zoro.lan
          description: "Nginx and Adguard server"
          ansible_user: callum
          machine_type: server

        nami:
          ansible_host: nami.lan
          description: "Media server"
          ansible_user: callum
          machine_type: server
          ansible_become_exe: sudo.ws # Ubuntu 26.04 uses sudo-rs instead of sudo... this makes it so it goes back to old sudo which is now called sudo.ws

        aerial:
          ansible_host: 140.238.84.179
          description: "Uptime server"
          ansible_user: ubuntu
          machine_type: server
          ansible_become_exe: sudo.ws # Ubuntu 26.04 uses sudo-rs instead of sudo... this makes it so it goes back to old sudo which is now called sudo.ws


    desktops:
      hosts:
        armin:
          ansible_host: armin.lan
          description: "My PC!"
          ansible_user: callum
          machine_type: desktop

#  vars:
#    ansible_user: callum
