services:
  app:
    container_name: "Nginx_Proxy_Manager"
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /config/letsencrypt/data:/data
      - /config/letsencrypt:/etc/letsencrypt

  uptime-kuma:
    container_name: "Uptime_Kuma"
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    volumes:
      - /config/uptime-kuma/data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"

    # Needed to manage via portainer
  portainer_agent:
    image: portainer/agent:latest
    container_name: "Portainer_Agent"
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
