---
- name: Configure Fish
  hosts: all

  tasks:
    - name: Create Fish configuration directory
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.config/fish"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Deploy Fish configuration
      ansible.builtin.copy:
        src: ../files/fish/config.fish
        dest: "{{ ansible_facts.user_dir }}/.config/fish/config.fish"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
